# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d4b8214cb643d10c2e08b6d7fae706ea63fb6a8f7b76ad92b60b700045073cd14b4571ae0bfd59d8045723a1b853a52d6f334e2ebb79f1be22b32b4d25b8827d

test:
  secret_key_base: 086bb6250fbf474e3af58f50a01ed1525e0c1835f140d1ad48b25dbe2b60bfeadae6310f17a74c9ca0053df3584c267406423ac8d79303fc015426281f74f3e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
